### ISSUE TITLE
Flashlight/Lasers

### ISSUE THREAD

**Issue by xanaguy** [sebastiangabl/pd2-bot-weapons#10]
http://steamcommunity.com/sharedfiles/filedetails/?id=1190313977

I learned an interesting thing just earlier about this mod. It turns out, the flashlight/lasers are already preset at certain coordinates, that being 0,0,0 (X,Y,Z) right? Well, for Framing Frame Day 1/Art Gallery, those flashlights are obviously visible in the security room since the true origin coordinates lie there.

**Comment by segabl** [comment]
Yeah I figured this would happen yet I haven't seen it on any maps yet. I'll see if I can do something simple about it, otherwise it'll be on low priority.
