### ISSUE TITLE
This was an immediate crash upon starting the alaskan deal heist.

### ISSUE THREAD

**Issue by xanaguy** [sebastiangabl/pd2-bot-weapons#11]
Application has crashed: C++ exception
[string "core/lib/utils/corecode.lua"]:100: attempt to index local 'obj' (a number value)

SCRIPT STACK

functionCall() @mods/Bot Weapons/botweapons.lua:161
Update() @mods/base/req/core/DelayedCalls.lua:24
func() @mods/base/req/core/DelayedCalls.lua:10
Call() @mods/base/req/core/Hooks.lua:109
update() @mods/base/lua/GameSetup.lua:6
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:537

**Comment by xanaguy** [comment]
Also worth noting that every heist causes the crash.

**Comment by segabl** [comment]
Hopefully fixed now

**Comment by segabl** [comment]
Hopefully fixed now
