### ISSUE TITLE
Someone kept disconncting and rejoining. And eventually caused this strange crash.

### ISSUE THREAD

**Issue by xanaguy** [sebastiangabl/pd2-bot-weapons#12]
Application has crashed: C++ exception
[File] Cannot read from file "C:\Program Files (x86)\Steam\steamapps\common\PAYDAY 2\assets\all_48.bundle" => error code 998: Invalid access to memory location. (d:\jenkins\shared-workspace\diesel\engine\dieselx\dieselx\blobs\../utility/Archive.cpp:2470)

SCRIPT_STACK

set_character() lib/units/armorskinext.lua:282
set_character_anim_variables() lib/units/beings/player/huskplayermovement.lua:318
set_unit() lib/network/base/networkpeer.lua:2276
spawn_unit_original() lib/network/base/networkpeer.lua:2132
spawn_unit() @mods/Bot Weapons/lua/networkpeer.lua:5
_spawn_dropin_player() lib/network/base/hostnetworksession.lua:701
chk_spawn_member_unit() lib/network/base/hostnetworksession.lua:680
lib/network/base/hostnetworksession.lua:287

-------------------------------

Callstack:

         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
               set_character()  lib/units/armorskinext.lua:282                      
set_character_anim_variables()  lib/units/beings/player/huskplayermovement.lua:318  
                    set_unit()  lib/network/base/networkpeer.lua:2276               
         spawn_unit_original()  lib/network/base/networkpeer.lua:2132               
                  spawn_unit()  @mods/Bot                                           
                                Weapons/lua/networkpeer.lua:5                       
        _spawn_dropin_player()                                                      
lib/network/base/hostnetworksession.lua:701  chk_spawn_member_unit()                             
                                lib/network/base/hostnetworksession.lua:680         
lib/network/base/hostnetworksession.lua:287  
-------------------------------

**Comment by xanaguy** [comment]
Ok, since this freaking issue page wont show the full crash, I am just going to resort to pastebin since it seems to be more reliable. https://pastebin.com/ep5fzL9x

**Comment by segabl** [comment]
I'm not sure this is an issue with my mod, this looks more like a mod override issue or an issue with some mod that changes armor or armor skins.
