### ISSUE TITLE
Repeating history

### ISSUE THREAD

**Issue by xanaguy** [sebastiangabl/pd2-bot-weapons#13]
Gonna have to reopen this since a similar thing is happening when a player joins in. This time is happened when a bot was in custody and I think that was the bot to be replaced by a joining player.  

https://pastebin.com/AMqePNFb

**Comment by segabl** [comment]
I will try to reproduce it though there shouldn't be an issue regarding that since the bots unit isn't loaded at that point.

**Comment by xanaguy** [comment]
Just saw a streamer crash under the exact same circumstances. He was unmodded, so I can confirm that this is a pure vanilla issue. Sorry to have wasted your time. Closing issue now.
