### ISSUE TITLE
Request for "old" npc weapons

### ISSUE THREAD

**Issue by xanaguy** [sebastiangabl/pd2-bot-weapons#14]
Do you think it's possible to also include any NPC specific weapons like the specifically attached Car-4 or the Light Swat's (and Cloaker's) Compact 5, shotguns, etc? (Even as its own separate group?)

**Comment by xanaguy** [comment]
Yes. I do mean pre-henchman update along with usage of very specific weapons like the Cloaker's Compact 5

**Comment by segabl** [comment]
Possible, yes not sure why you'd want that though. And an unneccessary amount of work to get them back properly.

**Comment by xanaguy** [comment]
Im merely curious to experiment with different weapons with bots (NPC exclusive and otherwise) with various settings and mods. Mostly to see which one triumphs over the setup I currently have now.
