### ISSUE TITLE
Conflicts with "More Weapon Categories"/"Custom Categories for Custom Weapons"

### ISSUE THREAD

**Issue by the-almighty-carl** [sebastiangabl/pd2-bot-weapons#17]
See the title. Killerwolf made a mod that adds, well, more weapon categories to the game so it's 1000x easier to find things in the blackmarket menu because you don't have to wade through NEARLY as much crap to get to what you want. The only problem with this is that, for some reason, when BW&E checks whether or not a weapon can be used by team AI it checks against a list of _allowed_ weapon categories instead of _disallowed_ weapon categories.

An easy 10-15 minute fix would be to either change the list so that it's a list of disallowed categories and change the conditions of the handful of functions that use the list accordingly. An even **easier** and arguably faster fix would be to just set up a hook that adds appropriate custom categories if an installation of MWC/CCFCW is detected to the allowed category list.

For the record, Killerwolf already had to do something similar to the aforementioned checks but in reverse to prevent BW&E crashing the game if you give a bot the RPK with MWC installed so the burden of bugfixing goes here instead of on his end. Probably.

**Comment by segabl** [comment]
So from what I've seen, his mod just changes the primary category of the weapons and keeps the original categories as well. My code (as well as vanilla for that matter) just checks the primary category so it should be an easy fix to check the complete category list.

**Comment by segabl** [comment]
Should be fixed in fb41ffa
