### ISSUE TITLE
attempt to index field 'color_a' (a nil value)

### ISSUE THREAD

**Issue by Krasna45** [sebastiangabl/pd2-bot-weapons#23]
Crashes when bots equip masks, be it in heist or entering henchmen menu

> Application has crashed: C++ exception
> [string "lib/units/maskext.lua"]:40: attempt to index field 'color_a' (a nil value)
> 
> SCRIPT STACK
> 
> ready_clbk() lib/managers/menu/menuscenemanager.lua:1961
> clbk() lib/managers/menu/menuscenemanager.lua:2058
> lib/managers/dynamicresourcemanager.lua:220

**Comment by segabl** [comment]
Make sure you remove any old versions of the mod and download the latest version manually
