### ISSUE TITLE
Discovered that this mod suddenly crashes Shadow Raid. 

### ISSUE THREAD

**Issue by Jayckal** [sebastiangabl/pd2-bot-weapons#24]
Whenever this mod is installed, Shadow Raid crashes on the preplanning screen 100% of the time. Looking at the crash.txt though, I can't find exactly why that is.

Application has crashed: C++ exception
[string "lib/units/enemies/cop/logics/coplogictravel.lua"]:135: attempt to index a nil value

SCRIPT STACK

enter() @mods/Iter/lua/coplogictravel.lua:22
set_logic() lib/units/enemies/cop/copbrain.lua:390
_exit() lib/units/enemies/cop/logics/coplogicbase.lua:198
on_new_objective() lib/units/enemies/cop/logics/coplogicidle.lua:483
set_objective() lib/units/enemies/cop/copbrain.lua:268
_administer_objective() lib/managers/mission/elementspecialobjective.lua:682
on_executed() lib/managers/mission/elementspecialobjective.lua:277
_execute_random_SO() lib/managers/mission/elementspecialobjectivegroup.lua:145
on_executed() lib/managers/mission/elementspecialobjectivegroup.lua:55
execute_on_executed() core/lib/managers/mission/coremissionscriptelement.lua:209
_trigger_execute_on_executed() core/lib/managers/mission/coremissionscriptelement.lua:147
on_executed() core/lib/managers/mission/coremissionscriptelement.lua:131
on_executed() lib/managers/mission/missionscriptelement.lua:18
callback() lib/managers/mission/elementenemydummytrigger.lua:21
event() lib/managers/mission/elementspawnenemydummy.lua:132
produce() lib/managers/mission/elementspawnenemydummy.lua:111
on_executed() lib/managers/mission/elementspawnenemygroup.lua:90
execute_on_executed() core/lib/managers/mission/coremissionscriptelement.lua:209
_trigger_execute_on_executed() core/lib/managers/mission/coremissionscriptelement.lua:147
on_executed() core/lib/managers/mission/coremissionscriptelement.lua:131
on_executed() lib/managers/mission/missionscriptelement.lua:18
execute_on_executed() core/lib/managers/mission/coremissionscriptelement.lua:209
_trigger_execute_on_executed() core/lib/managers/mission/coremissionscriptelement.lua:147
on_executed() core/lib/managers/mission/coremissionscriptelement.lua:131
on_executed() lib/managers/mission/missionscriptelement.lua:18
execute_on_executed() core/lib/managers/mission/coremissionscriptelement.lua:209
_trigger_execute_on_executed() core/lib/managers/mission/coremissionscriptelement.lua:147
on_executed() core/lib/managers/mission/coremissionscriptelement.lua:131
f() lib/managers/mission/missionscriptelement.lua:18
update() core/lib/utils/coreevent.lua:158
update() core/lib/managers/mission/coremissionmanager.lua:531
update() core/lib/managers/mission/coremissionmanager.lua:160
core/lib/setups/coresetup.lua:520

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
                         ntdll  (???)     LdrLoadEnclaveModule                                
                         ntdll  (???)     LdrLoadEnclaveModule  

Any help or am I just boned with this mod on Shadow Raid?

**Comment by segabl** [comment]
This looks more like a problem with Iter (or the combination of Iter and Bot Weapons), I'll give it a try and notify the author of iter in case I can reproduce it.

**Comment by Jayckal** [comment]
> This looks more like a problem with Iter (or the combination of Iter and Bot Weapons), I'll give it a try and notify the author of iter in case I can reproduce it.

I've deleted Iter and kept this mod only for the same crash to happen. After deleting this mod, the heist started up as normal, even with Iter installed. Whatever is causing this to happen is quite an odd thing.

**Comment by segabl** [comment]
And you're sure this is the exact crash when you enter preplanning? Nothing like that code should be executed while you're not ingame.

**Comment by Jayckal** [comment]
> And you're sure this is the exact crash when you enter preplanning? Nothing like that code should be executed while you're not ingame.

Not even preplanning, sorry. It crashes as soon as it loads into the pre-beginning menu. Y'know, where you can select pre-planning and buy assets? Just before that little animation to the left of that menu plays, it crashes.

**Comment by segabl** [comment]
Hmm at that point none of the bot code actually runs, as the bots are only spawned when you enter the game. Do you have a specific setup for your bots? I could load and play Shadow raid just fine.

**Comment by Jayckal** [comment]
Bots have base game weapons, one has the Raven, another the JP36 and the third one has the R93. Abilities are Sharpeyed, Quick and inspiring where as the boosts are Healer, Invigorator and Accelerator.

I'll give it another shot, maybe I screwed something up.

Edit: Still crashes in much the same way.

**Comment by segabl** [comment]
then there must be some other mod involved that causes this. as it actually crashes on setting a objective on some guard I assume.

**Comment by Jayckal** [comment]
> then there must be some other mod involved that causes this. as it actually crashes on setting a objective on some guard I assume.

Oh, well. Thank you for trying to help and I apologize for wasting your time. I'll try to see if I can't do anything else to fix it or if it's just Shadow Raid putting me in the naughty corner.

**Comment by segabl** [comment]
If you can show me your mod list I can give you some hints on what to check

**Comment by Jayckal** [comment]
> If you can show me your mod list I can give you some hints on what to check

<img width="465" alt="Mod list - 2" src="https://user-images.githubusercontent.com/76649270/103174826-7d899f00-4865-11eb-89d9-3bb5e65f181a.png">
<img width="413" alt="Mod list - 1" src="https://user-images.githubusercontent.com/76649270/103174827-7e223580-4865-11eb-8ca5-1d68ee4a9308.png">

**Comment by segabl** [comment]
Hm nothing that really catches my eye, especially not that would cause anything like this in combination with bot weapons. can you check your blt logs for any errors or warnings?

**Comment by Jayckal** [comment]
> Hm nothing that really catches my eye, especially not that would cause anything like this in combination with bot weapons. can you check your blt logs for any errors or warnings?

Nothing out of the ordinary other than some missing weapon icons, according to the BLT logs.

**Comment by segabl** [comment]
Not sure what the issue could be then, sorry.

**Comment by Jayckal** [comment]
> Not sure what the issue could be then, sorry.

That's quite alright, thank you for trying.
