### ISSUE TITLE
Crashes on sertain heist when Fix Team Ai Weapon Balance option is enabled.

### ISSUE THREAD

**Issue by sirben99** [sebastiangabl/pd2-bot-weapons#25]
Hey!

I tested to see what mod causes the crashes im having on Beneath the mountain (and Whitehouse if i remember correctly) heists. Then after about hour of testing what might cause it, it was this mod. I tested the options and when the above option is disabled, the game doesent crash anymore. I gave the bots stock AMCAR weapons to see if it was a weapon i gave them, but no, same result. I have other mods installed say maybe a conflict but i cant pinpoint where, since i have a lot of them. But if you want, i can go though the progress of deleting them one by one, just to see what causes it.

Heres the crashlog: 

Application has crashed: C++ exception
[string "lib/units/enemies/cop/logics/coplogictravel.lua"]:135: attempt to index a nil value

SCRIPT STACK

set_logic() lib/units/enemies/cop/copbrain.lua:390
_exit() lib/units/enemies/cop/logics/coplogicbase.lua:198
on_new_objective() lib/units/enemies/cop/logics/coplogicidle.lua:483
set_objective() lib/units/enemies/cop/copbrain.lua:268
_administer_objective() lib/managers/mission/elementspecialobjective.lua:682
on_executed() lib/managers/mission/elementspecialobjective.lua:277
execute_on_executed() core/lib/managers/mission/coremissionscriptelement.lua:209
_trigger_execute_on_executed() core/lib/managers/mission/coremissionscriptelement.lua:147
on_executed() core/lib/managers/mission/coremissionscriptelement.lua:131
on_executed() lib/managers/mission/missionscriptelement.lua:18
on_executed() lib/managers/mission/elementspawnenemydummy.lua:150
execute_on_executed() core/lib/managers/mission/coremissionscriptelement.lua:209
_trigger_execute_on_executed() core/lib/managers/mission/coremissionscriptelement.lua:147
on_executed() core/lib/managers/mission/coremissionscriptelement.lua:131
on_executed() lib/managers/mission/missionscriptelement.lua:18
on_executed() core/lib/managers/mission/coreelementrandom.lua:39
execute_on_executed() core/lib/managers/mission/coremissionscriptelement.lua:209
_trigger_execute_on_executed() core/lib/managers/mission/coremissionscriptelement.lua:147
on_executed() core/lib/managers/mission/coremissionscriptelement.lua:131
on_executed() lib/managers/mission/missionscriptelement.lua:18
execute_on_executed() core/lib/managers/mission/coremissionscriptelement.lua:209
_trigger_execute_on_executed() core/lib/managers/mission/coremissionscriptelement.lua:147
on_executed() core/lib/managers/mission/coremissionscriptelement.lua:131
on_executed() lib/managers/mission/missionscriptelement.lua:18
on_executed() core/lib/managers/mission/coreelementarea.lua:121
_check_amount() core/lib/managers/mission/coreelementarea.lua:270
f() core/lib/managers/mission/coreelementarea.lua:235
update() core/lib/utils/coreevent.lua:158
update() core/lib/managers/mission/coremissionmanager.lua:531
update() core/lib/managers/mission/coremissionmanager.lua:160
original() core/lib/setups/coresetup.lua:520
@mods/base/req/core/Hooks.lua:265

I saw on the modpage that you prefer to send any problems here, so i desided to post this in here. If theres any other unformation you need please let me know!

EDIT: Also crashes on shadowraid, right in the planning screen. I saw another person mention this in the issues. Im going to look if we have a same mod that conflicts with this one.

EDIT 2: Okay, i think i have an assumption of whats causing it. Its either WeaponLib or a weapon in mod_overrides based on the previes issue maker. This is going to be an painful one to track down

**Comment by segabl** [comment]
I would assume it has something to do with murky enemies then. possibly something that modifies their weapons? this mod shouldn't touch npc weapons at all but if it's a conflict with another mod, it may get confused. I'll see if I can reproduce this crash.

**Comment by sirben99** [comment]
> I would assume it has something to do with murky enemies then. possibly something that modifies their weapons? this mod shouldn't touch npc weapons at all but if it's a conflict with another mod, it may get confused. I'll see if I can reproduce this crash.

Yeah i managed to tracked down to mod_overrides folder. Wich is 20 gigs big. But i have some non-weapons mods in it, so ill test with those to see if its a mod mod or a weapon mod. And yes this occurs on murky heists

**Comment by sirben99** [comment]
I managed to track it down even further. Its possible an weapon or weapon mod. That i have 561. Welp, time to see what causes it. God help me

**Comment by segabl** [comment]
jesus christ, how is it even possible to have 561 weapon mods and not run out of memory

**Comment by sirben99** [comment]
> jesus christ, how is it even possible to have 561 weapon mods and not run out of memory

Tbh i have no idea. Im now trying to see what crassesh 50 mods at a time.

**Comment by sirben99** [comment]
I FOUND THE MOD THAT CRASHES THE GAME

https://modworkshop.net/mod/17330

This took hours. But i managed to found it. Game no longer crashes in the heist even with over 600 mods. I hope this helps!

**Comment by segabl** [comment]
Oh nice, I'll have a look at this. Given how old this mod is, it probably adds npc stats for the ump which override the actual ump stats the game already has. Correction: Actually beardlib's fault for copying over npc values it really shouldn't do.
