### ISSUE TITLE
crew abilities + crew boosts issue

### ISSUE THREAD

**Issue by Sniper677** [sebastiangabl/pd2-bot-weapons#26]
I am facing the issue that crew abilities + crew boosts for LOADOUT2 and LOADOUT3 is the same in all 15 profiles.
I cleared all character loadouts and unset all crew abilities + boosts in all 15 profiles manually.
I restarted the game and immediately after clean start and setting ability and/or boost in loadout 2 or 3 for the 1st time it is also set in all other profiles.

**Comment by Sniper677** [comment]
okay new finding is, it seems to be related to other mods. when I start game only with BWE and clearing all profiles + crew abilities/boosts it does not happen.

is there a way to debug the issue?

**Comment by segabl** [comment]
Well, a good way would be to check what other mods you have installed that could potentially cause this issue. Any  mods that change crew management, loadout profiles etc.

**Comment by Sniper677** [comment]
it took me a while, but i found it. your mod is clean it did not produce the issue. there i close this here. thanks for your feedback
