### ISSUE TITLE
Fresh Install Armor Skin Console Spam

### ISSUE THREAD

**Issue by connieprice** [sebastiangabl/pd2-bot-weapons#28]
If you've never selected an armor skin to give to your AI, your console is constantly filled with:

![image](https://user-images.githubusercontent.com/5340283/127986435-c19428b0-61b9-4150-b866-e65719f32a68.png)

Ideally, I shouldn't *have* to select an armor skin to not have my console be filled with crap by default.

**Comment by segabl** [comment]
Ah yeah, that's an issue with the check I see. Stuff you never encounter as the mod dev.
