### ISSUE TITLE
Bot weapon equip issue (all bots equip whatever weapon the first bot has)

### ISSUE THREAD

**Issue by ShinyRayquaza9** [sebastiangabl/pd2-bot-weapons#31]
this happens as of the newest update to the mod

**Comment by segabl** [comment]
I cannot reproduce this, can you tell me your bot setup?

**Comment by ShinyRayquaza9** [comment]
What specifically about them, also just realized that I could've had this issue before and not noticed as I usually have all three on izthma shotgun

**Comment by segabl** [comment]
basically what you have set them to and any other settings you use in the mod

**Comment by ShinyRayquaza9** [comment]
Figured it out, its the custom bain and locke heister mods, for some reason
when they are used, they copy the first ai's weapon
