### ISSUE TITLE
The option when marked FIX TEAM AI WEAPON BALANCE Make crash

### ISSUE THREAD

**Issue by ChrisLeons** [sebastiangabl/pd2-bot-weapons#33]
The option when marked
FIX TEAM AI WEAPON BALANCE
Make crash

Application has crashed: C++ exception
[string "lib/units/enemies/cop/copmovement.lua"]:2766: attempt to index local 'weapon_usage_tweak' (a nil value)

SCRIPT STACK

clbk() @mods/base/req/core/Hooks.lua:260
call() lib/utils/eventlistenerholder.lua:34
_call_listeners() lib/units/beings/player/playerinventory.lua:698
equip_selection() lib/units/beings/player/playerinventory.lua:536
equip_selection() lib/units/player_team/teamaiinventory.lua:114
post_init() lib/units/enemies/cop/copmovement.lua:596
old_post() lib/units/player_team/teamaibase.lua:7
post_init() @mods/Better Bots/betterbots.lua:194
lib/units/player_team/teamaisound.lua:5
spawn_unit() =[C]
spawn_one_teamAI() lib/managers/group_ai_states/groupaistatebase.lua:3061
fill_criminal_team_with_AI() lib/managers/group_ai_states/groupaistatebase.lua:3392
spawn_players() lib/network/base/basenetworksession.lua:1524
update() lib/states/ingamewaitingforplayers.lua:310
update() core/lib/utils/game_state_machine/coregamestatemachine.lua:92
update() lib/setups/setup.lua:940
original() lib/setups/gamesetup.lua:802
update() @mods/base/req/core/Hooks.lua:260
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:559

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlInitializeExceptionChain                         
                         ntdll  (???)     RtlClearBits                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.143.243
	CPU : Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz (6 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : AMD Radeon RX 580 2048SP / aticfx32.dll[31.0.21912.14]
	Language : portuguese
	Memory :     16225MB 76KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Alto-falantes (2- H710 Audio Device))

**Comment by segabl** [comment]
I see you are using Better Bots which is years outdated, contains its own balance changes and is probably the reason for the crash

**Comment by ChrisLeons** [comment]
Yes
