### ISSUE TITLE
Crash When Player Joins

### ISSUE THREAD

**Issue by NerdVenom** [sebastiangabl/pd2-bot-weapons#4]
Bots have Default Masks and Reinfields in Crew Management. Various Armors and masks in mod options. I tried setting them all to use the just Reinfields with the override but I still crash.

crash.txt
`Application has crashed: C++ exception
mods/BeardLib/Classes/utils.lua:273: attempt to index field 'primary' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name`

**Comment by segabl** [comment]
This was a BeardLib issue that should be fixed by now.
