### ISSUE TITLE
Crash when giving bot a bag (U151.2)

### ISSUE THREAD

**Issue by VxWolf** [sebastiangabl/pd2-bot-weapons#5]
Application has crashed: C++ exception
    mods/Bot Weapons/lua/teamaimovement.lua:69: attempt to index a nil value
    
    
    
    SCRIPT STACK
    
    
    
    -------------------------------
    
    Callstack:
    
             payday2_win32_release  (???)     ???                                                 
             payday2_win32_release  (???)     ???                                                 
             payday2_win32_release  (???)     ???                                                 
             payday2_win32_release  (???)     zip_get_name                                        
                             ntdll  (???)     RtlAllocateHeap                                     
                               ???  (???)     ???

**Comment by segabl** [comment]
I cannot reproduce the crash, are you using any HUD mods? Did you tick "Bots carry bags like players"?

**Comment by segabl** [comment]
I assume this does not occur anymore. I also included a sanity check in that part of code so it doesn't crash if for some reason there's no name label.
