### ISSUE TITLE
Keeps Asking to Update

### ISSUE THREAD

**Issue by NerdVenom** [sebastiangabl/pd2-bot-weapons#6]
Doesn't matter if I just updated, Bot Weapons asks to update every time. I've tried getting a fresh copy and it still does this.

**Comment by segabl** [comment]
Are you using the armor skins addon by Dr_Newbie? It changes some of the source files of this mod which makes BLT think there's a new version.

**Comment by NerdVenom** [comment]
Yes, I am using that mod. So it's an issue with that mod instead?

**Comment by segabl** [comment]
Yes, Dr_Newbie decided to change the source code of this mod from within his mod which triggers the "update". I already wrote a comment on his mod's page suggesting a different solution.

**Comment by NerdVenom** [comment]
Alright, thanks for the info.
