### ISSUE TITLE
Character loadout masks don't save

### ISSUE THREAD

**Issue by Kuziz** [sebastiangabl/pd2-bot-weapons#7]
So I choose a bot I want to give a unique loadout, I attempt to give it a mask from a set, in this example a mega mask. It shows up. I apply loadout to characters to save it, mask gets reset to their character preferred. Same thing happens to all the mask sets and random mask option.

Works fine if it's a mask picked manually from your inventory.
Started happening not so long ago, I think after the Sangres shirt feature was added?

Video of the bug in gfycat link: https://gfycat.com/WeeShamelessAntlion

**Comment by segabl** [comment]
Yes, during optimizing the code I made a small mistake that bugged out random selections when used as unique loadout. I will push a fix today.
