### ISSUE TITLE
Rare crash?

### ISSUE THREAD

**Issue by xanaguy** [sebastiangabl/pd2-bot-weapons#9]
Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                functionCall()  @mods/Bot                                           
                                Weapons/botweapons.lua:138                          
                      Update()                                                      
@mods/base/req/core/DelayedCalls.lua:24  func()                                              
                                @mods/base/req/core/DelayedCalls.lua:10             
                        Call()                                                      
@mods/base/req/core/Hooks.lua:109  update()                                            
                                @mods/base/lua/GameSetup.lua:6                      
                      update()                                                      
lib/setups/networkgamesetup.lua:21  core/lib/setups/coresetup.lua:537                   

Moments before the crash, someone joined and the game froze as normal. At the same time, someone else dc'd during the freeze. Once that person spawned in (which is right after the freeze frame) the crash occurred.

**Comment by xanaguy** [comment]
My guess? Likely that the bot disappearing to be replaced by the joining player and the bot reappearing after someone else DC'd were using the same loadout. And that couldn't happen?

**Comment by segabl** [comment]
I think it's happening when a bot spawns in and is replaced immeditately after. I've pushed an update, please reopen if it still happens.
